In [2]:
#pip install numpy
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [4]:
#ndarray means n dimesion

In [13]:
import time

#excution performance
size = 1_000_000

#python list
py_list = list(range(size))
start = time.time()
sq_list = {x**2 for x in py_list}
end = time.time()
print(f"Python list time = {end-start} seconds")

#Numpy array
np_arr = np.array(py_list)
start = time.time()
#vectorization
sq_array = np_arr **2
end = time.time()
print(f"Numpy Array time = {end-start} seconds")

Python list time = 0.3092033863067627 seconds
Numpy Array time = 0.0029833316802978516 seconds


In [10]:
#memory

import sys

print(f"Python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"Numpy array size = {np_arr.nbytes} bytes")

Python list size = 8000056000000 bytes
Numpy array size = 8000000 bytes


In [12]:
#create  - form list

arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.shape)

arr2 = np.array([1, 2, 3, 4, 5, "print"])
print(arr, type(arr), arr.shape)

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [25]:
#create
arr1 = np.zeros((2,3), dtype="int64")  #prefill
print(arr1, arr1.shape)

arr2 = np.ones((5, ))  #prefill
print(arr2, arr2.shape)

arr3 = np.full((3, 4), 100) #prefill with val
print(arr3, arr3.shape)

arr4 = np.eye(3)  #identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(0, 10, 2)  #range elements
print(arr5, arr5.shape)

arr6 = np.linspace(1, 100, 3)        #evenly spaced arrays
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[0 2 4 6 8] (5,)
[  1.   50.5 100. ] (3,)


In [30]:
#properties
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr.shape)      #dimensions of m x n
print(arr.size)        # total elements
print(arr.dtype)  
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [33]:
#Operations on arrays

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, arr.shape)

reshaped = arr.reshape((3, 2))
print(reshaped, reshaped.shape)

flattened = arr.flatten()  #2D -> 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [35]:
#Indexing

#1D array
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[3])

#2D array

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1[1][1])
print(arr1[0][2])

1
4
5
3


In [39]:
#Fancy Indexing

arr = np.array([1, 2, 3, 4, 5])

idx = [0, 1, 3]
print(arr[idx])

# Boolean Indexing
print(arr[arr > 3])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

[1 2 4]
[4 5]
[2 4]
[1 3 5]


In [41]:
#Slicing 

arr = np.array([1, 2, 3, 4, 5])

print(arr[1:4])    #[start, end, stop]
print(arr[1:])
print(arr[ :4])
print(arr[ : :2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]


In [45]:
#Copy Vs View
#PyList Copy
nums = [1, 2, 3, 4, 5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200

print(sub_list)
print(nums)

#Numpy View
arr = np.array([1, 2, 3, 4, 5])
sub_arr = arr[1:3]
print(sub_arr)

sub_arr[0] = 200
print(sub_arr)
print(arr)

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
[2 3]
[200   3]
[  1 200   3   4   5]


In [54]:
#Data Types
arr = np.array([1, 2, 3, 4, 5])
print(arr, arr.dtype)

arr1 = np.array([1, 2, 3, 41.1, 5])
print(arr1, arr1.dtype)

arr2 = np.array([1, 2, 3, 4, "print"])
print(arr2, arr2.dtype)

arr3 = np.array([3 + 5j])
print(arr3, arr3.dtype)

arr4 = np.array(["prime", {1, 2, 3}, 3.10])
print(arr4, arr4.dtype)

[1 2 3 4 5] int64
[ 1.   2.   3.  41.1  5. ] float64
['1' '2' '3' '4' 'print'] <U21
[3.+5.j] complex128
['prime' {1, 2, 3} 3.1] object


In [60]:
#Multi-Dimensional Arrays

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D)
print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [74]:
#3D Arrays
arr3D = np.array([[[1, 2,], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])   # 2 x 3 x 2

print(arr3D, arr3D.shape)

#indexing
print(arr3D[0, 1, 1])
print(arr3D[1, 1, 0])

#slicing
print(arr3D[:, 0, :])   #first row from both layer
print(arr3D[:, :, 0])   #first column from both layer

arr3D[:, 0, :] = 99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [77]:
#vectorization

arr = np.array([1, 2, 3, 4, 5, 6])
arr1 = np.array([7, 8, 9, 10, 11, 12])

print(arr**2)
print(arr + 10)

print(arr + arr1)

[ 1  4  9 16 25 36]
[11 12 13 14 15 16]
[ 8 10 12 14 16 18]


In [79]:
#broadcasting

arr = np.array([1, 2, 3, 4, 5])
arr1 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])

print(arr.shape)
print(arr1.shape)

print(arr + arr1)

(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [82]:
#normalize
arr = np.array([[1, 2], [3, 4]])

print(np.mean(arr))
print(np.std(arr))

mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr - mean)/std_dev

print(normalized_arr)

2.5
1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [89]:
#mathematical funcation

#aggregation
arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))

print(np.std(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
1.4142135623730951
3.0
3.0
2.0


In [91]:
#power funcation

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr, 3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [94]:
#log

print(np.log(arr))
print(np.log10(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [103]:
#rounding

print(np.round(3.14))
print(np.round(3.94))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

arr = np.array([1, 2, 3, 4, 5, 2, 4, 3, 8])
print(np.unique(arr))
print(np.sort(arr))

print(np.abs(arr))

3.0
4.0
4.0
3.0
3.0
[1 2 3 4 5 8]
[1 2 2 3 3 4 4 5 8]
[1 2 3 4 5 2 4 3 8]
